[package]
name = "kaizen"
version = "0.1.0"
authors = ["Owen Nelson <onelson@gmail.com>"]

[dependencies]
diesel = "0.12.0"
iron = "0.5.1"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"
git2 = "0.6.4"

